# Creates Docker containers suited for development
version: '3.0'
services:

  # Lohpi-DV 
  lohpi-directoryserver:
    container_name: lohpi-directoryserver
    image: lohpi-directoryserver
    build: 
      context: .
      dockerfile: "./cmd/directoryserver/Dockerfile"
    command: ./config/lohpi_config.dev.yaml
    #restart: never
    expose:
    - "8080"
    - "8081"
    - "5000"
    - "8000"

  # Lohpi-DV 
  lohpi-policy-store-dev:
    environment:
      - LOHPI_ENV=development
    container_name: lohpi-policy-store-dev
    image: lohpi-policy-store-dev
    build:
      context: .
      dockerfile: "./cmd/policy_store/Dockerfile"
    network_mode: host
    command: -new=true -c ./config/lohpi_config.dev.yaml
    #restart: never
    expose:
      - "8083"
    depends_on:
      - lohpi-ca-dev
      - lohpi-directoryserver-dev

  # Lohpi-DV     
  lohpi-azureblobnode-dev:
    environment:
      - LOHPI_ENV=development
    container_name: lohpi-azureblobnode-dev
    image: lohpi-azureblobnode-dev
    build: 
      context: .
      dockerfile: "./cmd/azureblobnode/Dockerfile"
    network_mode: host
    #restart: never
    command: -name "azureblobnode" -new=true -c ./config/lohpi_config.dev.yaml
    depends_on: 
      - lohpi-ca-dev
      - lohpi-directoryserver-dev
      - lohpi-policy-store-dev
