version: '3.0'
services:

  # Lohpi-DV 
  ca:
    environment:
      - LOHPI_ENV=production
    container_name: lohpi-ca
    image: lohpi.azurecr.io/lohpi-ca
    build: 
      context: .
      dockerfile: "./cmd/ca/Dockerfile"
    command: --new
    network_mode: host
    restart: unless-stopped
    expose:
      - "8300"
      - "8301"
  
  # Lohpi-DV 
  directoryserver:
    environment:
      - LOHPI_ENV=production
    container_name: lohpi-directoryserver
    image: lohpi.azurecr.io/lohpi-directoryserver
    build: 
      context: .
      dockerfile: "./cmd/directoryserver/Dockerfile"
    network_mode: host
    command: 
      - --new
    restart: unless-stopped
    expose:
    - "8080"
    depends_on: 
    - ca

  # Lohpi-DV 
  policy_store:
    environment:
      - LOHPI_ENV=production
    container_name: lohpi-policy-store
    image: lohpi.azurecr.io/lohpi-policy-store
    build:
      context: .
      dockerfile: "./cmd/policy_store/Dockerfile"
    network_mode: host
    command: -new=true
    restart: unless-stopped
    expose:
      - "8083"
    depends_on:
      - ca
      - directoryserver

  # Lohpi-DV     
  dv-node:
    environment:
      - LOHPI_ENV=production
    container_name: lohpi-node-1
    image: lohpi.azurecr.io/lohpi-node-1
    build: 
      context: .
      dockerfile: "./cmd/dataversenode/Dockerfile"
    network_mode: host
    restart: unless-stopped
    command: -name "node_1" -new=true -c lohpi_config/lohpi_config.yaml
    depends_on: 
    - ca
    - directoryserver
    - policy_store

    # Lohpi-DV 
  azureblob-node:
    environment:
      - LOHPI_ENV=production
    container_name: lohpi-node-2
    image: lohpi.azurecr.io/lohpi-node-2
    build: 
      context: .
      dockerfile: "./cmd/azureblobnode/Dockerfile"
    network_mode: host
    restart: unless-stopped
    command: -name "node_2" -new=true -c lohpi_config/lohpi_config.yaml
    depends_on: 
      - ca
      - directoryserver
      - policy_store