version: '3.0'
services:

  # Lohpi-DV 
  dv-ca:
    container_name: lohpi-ca
    image: lohpi.azurecr.io/lohpi-ca
    build: 
      context: .
      dockerfile: "./cmd/dataverse/ca/Dockerfile"
    command: --new
    network_mode: host
    restart: unless-stopped
    expose:
      - "8300"
      - "8301"
  
  # Lohpi-DV 
  dv-directoryserver:
    container_name: lohpi-directoryserver
    image: lohpi.azurecr.io/lohpi-directoryserver
    build: 
      context: .
      dockerfile: "./cmd/dataverse/directoryserver/Dockerfile"
    network_mode: host
    command: --new
    restart: unless-stopped
    expose:
    - "8080"
    depends_on: 
    - dv-ca

  # Lohpi-DV 
  dv-policy_store:
    container_name: lohpi-policy-store
    image: lohpi.azurecr.io/lohpi-policy-store
    build:
      context: .
      dockerfile: "./cmd/dataverse/policy_store/Dockerfile"
    network_mode: host
    command: -new=true
    restart: unless-stopped
    expose:
      - "8083"
    depends_on:
      - dv-ca
      - dv-directoryserver

  # Lohpi-DV     
  dv-node:
    container_name: lohpi-node
    image: lohpi.azurecr.io/lohpi-node
    build: 
      context: .
      dockerfile: "./cmd/dataverse/node/Dockerfile"
    network_mode: host
    restart: unless-stopped
    command: -name "node_0" -new=true
    depends_on: 
    - dv-ca
    - dv-directoryserver
    - dv-policy_store
