# Creates Docker containers suited for development
version: '3.0'
services:

  # Lohpi-DV 
  lohpi-ca-dev:
    environment:
      - LOHPI_ENV=development
    container_name: lohpi-ca-dev
    image: lohpi-ca-dev
    build: 
      context: .
      dockerfile: "./cmd/ca/Dockerfile"
    command: --new
    network_mode: host
    #restart: 
    expose:
      - "8300"
      - "8301"
  
  # Lohpi-DV 
  lohpi-directoryserver-dev:
    environment:
      - LOHPI_ENV=development
    container_name: lohpi-directoryserver-dev
    image: lohpi-directoryserver-dev
    build: 
      context: .
      dockerfile: "./cmd/directoryserver/Dockerfile"
    network_mode: host
    command: --new -c ./config/lohpi_config.dev.yaml
    #restart: never
    expose:
      - "8080"
      - "8081"
      - "5000"
      - "8000"
    depends_on: 
      - lohpi-ca-dev

  # Directory server Redis cache
  lohpi-directoryserver-redis:
    image: "redis:alpine"
    command: redis-server --port 6302
    ports:
     - "6302:6302"
    environment:
      - REDIS_HOST=redis
    depends_on: 
      - lohpi-directoryserver-dev

  # Lohpi-DV 
  lohpi-policy-store-dev:
    environment:
      - LOHPI_ENV=development
    container_name: lohpi-policy-store-dev
    image: lohpi-policy-store-dev
    build:
      context: .
      dockerfile: "./cmd/policy_store/Dockerfile"
    network_mode: host
    command: -new=true -c ./config/lohpi_config.dev.yaml
    #restart: never
    expose:
      - "8083"
      - "8084"
    depends_on:
      - lohpi-ca-dev
      - lohpi-directoryserver-dev
 
  # Policy store Redis cache
  lohpi-policy-store-redis:
    image: "redis:alpine"
    command: redis-server --port 6301
    ports:
     - "6301:6301"
    environment:
      - REDIS_HOST=redis   
    depends_on:
      - lohpi-policy-store-dev

  # Lohpi-DV     
  lohpi-azureblobnode-dev:
    environment:
      - LOHPI_ENV=development
    container_name: lohpi-azureblobnode-dev
    image: lohpi-azureblobnode-dev
    build: 
      context: .
      dockerfile: "./cmd/azureblobnode/Dockerfile"
    network_mode: host
    restart: always
    command: -name "azureblobnode" -new=true -c ./config/lohpi_config.dev.yaml
    expose:
      - "8090"
    depends_on: 
      - lohpi-ca-dev
      - lohpi-directoryserver-dev
      - lohpi-policy-store-dev
  
  # Policy store Redis cache
  lohpi-azureblobnode-redis:
    image: "redis:alpine"
    command: redis-server --port 6300
    ports:
     - "6300:6300"
    environment:
      - REDIS_HOST=redis
    depends_on: 
      - lohpi-azureblobnode-dev
