package message

type MsgType string

// Different message types to be used internally in the Lohpi network
// TODO: use numbers instead to minimize message size
const (
	MSG_TYPE_GET_NODE_INFO              = "MSG_TYPE_GET_NODE_INFO"
	MSG_TYPE_GET_DATASET_INFO           = "MSG_TYPE_GET_DATASET_INFO"
	MSG_TYPE_INSERT_DATASET             = "MSG_TYPE_INSERT_DATASET"
	MSG_TYPE_GET_DATASET                = "MSG_TYPE_GET_DATASET"
	MSG_TYPE_MUX_HANDSHAKE              = "MSG_TYPE_MUX_HANDSHAKE"
	MSG_TYPE_PS_HANDSHAKE               = "MSG_TYPE_PS_HANDSHAKE"
	MSG_TYPE_GET_OBJECT_HEADER_LIST     = "MSG_TYPE_GET_OBJECT_HEADER_LIST"
	MSG_TYPE_GET_OBJECT_HEADER_IDS      = "MSG_TYPE_GET_OBJECT_HEADER_IDS"
	MSG_TYPE_GET_OBJECT                 = "MSG_TYPE_GET_OBJECT"
	MSG_TYPE_SET_STUDY_LIST             = "MSG_TYPE_SET_STUDY_LIST"
	MSG_TYPE_OBJECT_HEADER_LIST         = "MSG_TYPE_UPDATED_OBJECT_LIST"
	MSG_TYPE_GET_DATA                   = "MSG_TYPE_GET_DATA"
	MSG_TYPE_GET_META_DATA              = "MSG_TYPE_GET_META_DATA"
	MSG_TYPE_SET_MUX_IP                 = "MSG_TYPE_SET_MUX_IP"
	MSG_TYPE_OK                         = "MSG_TYPE_OK"
	MSG_TYPE_MONITORING_NODE            = "MSG_TYPE_MONITORING_NODE"
	MSG_TYPE_CHANGE_SUBJECT_POLICY      = "MSG_TYPE_CHANGE_SUBJECT_POLICY"
	MSG_TYPE_ERROR                      = "MSG_TYPE_ERROR"
	MSG_TYPE_SET_SUBJECT_POLICY         = "MSG_TYPE_SET_SUBJECT_POLICY"
	MSG_TYPE_SET_REC_POLICY             = "MSG_TYPE_SET_REC_POLICY"
	MSG_TYPE_SET_POLICY                 = "MSG_TYPE_SET_POLICY"
	MSG_TYPE_PROBE_ACK                  = "MSG_TYPE_PROBE_ACK"
	MSG_TYPE_PROBE                      = "MSG_TYPE_PROBE"
	MSG_TYPE_GOSSIP_MESSAGE             = "MSG_TYPE_GOSSIP_MESSAGE"
	MSG_TYPE_DATASET_EXISTS             = "MSG_TYPE_DATASET_EXISTS"
	MSG_TYPE_POLICY_STORE_UPDATE        = "MSG_TYPE_POLICY_STORE_UPDATE"
	MSG_TYPE_GET_DATASET_URL            = "MSG_TYPE_GET_DATASET_URL"
	MSG_TYPE_RESPONSE                   = "MSG_TYPE_RESPONSE"
	GOSSIP_MSG_TYPE_POLICY              = "GOSSIP_MSG_TYPE_POLICY"
	MSG_TYPE_LIST_DATAVERSES            = "MSG_TYPE_LIST_DATAVERSES"
	MSG_TYPE_GET_DATASET_IDENTIFIERS    = "MSG_TYPE_GET_DATASET_IDENTIFIERS"
	STREAM_STORAGE_OBJECT               = "STREAM_STORAGE_OBJECT"
	MSG_TYPE_GET_DATASET_POLICY         = "MSG_TYPE_GET_DATASET_POLICY"
	MSG_TYPE_GET_DATASET_METADATA_URL   = "MSG_TYPE_GET_DATASET_METADATA_URL"
	MSG_TYPE_GET_INITIAL_DATASET_POLICY = "MSG_TYPE_GET_INITIAL_DATASET_POLICY"
	MSG_TYPE_ADD_DATASET_IDENTIFIER     = "MSG_TYPE_ADD_DATASET_IDENTIFIER"
	MSG_TYPE_ROLLBACK_CHECKOUT          = "MSG_TYPE_ROLLBACK_CHECKOUT"
	MSG_POLICY_REVOCATION_UPDATE        = "MSG_POLICY_REVOCATION_UPDATE"

)
