// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	Msg
	MsgResponse
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Application message
type Msg struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Msg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// Application response
type MsgResponse struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *MsgResponse) Reset()                    { *m = MsgResponse{} }
func (m *MsgResponse) String() string            { return proto.CompactTextString(m) }
func (*MsgResponse) ProtoMessage()               {}
func (*MsgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg)(nil), "message.Msg")
	proto.RegisterType((*MsgResponse)(nil), "message.MsgResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Message service

type MessageClient interface {
	SendMsg(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*MsgResponse, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SendMsg(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := grpc.Invoke(ctx, "/message.message/SendMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Message service

type MessageServer interface {
	SendMsg(context.Context, *Msg) (*MsgResponse, error)
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.message/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendMsg(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _Message_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55,
	0x92, 0xe7, 0x62, 0xf6, 0x2d, 0x4e, 0x17, 0x92, 0xe0, 0x62, 0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcd,
	0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x95, 0xd4, 0xb9, 0xb8, 0x7d, 0x8b,
	0xd3, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x71, 0x2b, 0x34, 0xb2, 0xe2, 0x82, 0x19,
	0x2a, 0xa4, 0xcf, 0xc5, 0x1e, 0x9c, 0x9a, 0x97, 0x02, 0x32, 0x98, 0x47, 0x0f, 0x2a, 0xa8, 0xe7,
	0x5b, 0x9c, 0x2e, 0x25, 0x82, 0xcc, 0x83, 0x99, 0xa9, 0xc4, 0x90, 0xc4, 0x06, 0x76, 0x95, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x45, 0x46, 0xd6, 0xa3, 0x00, 0x00, 0x00,
}
