// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PolicyAttribute      []byte   `protobuf:"bytes,2,opt,name=policyAttribute,proto3" json:"policyAttribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetPolicyAttribute() []byte {
	if m != nil {
		return m.PolicyAttribute
	}
	return nil
}

// Used in direct messaging
type Message struct {
	Type            string           `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Sender          *Node            `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Policy          *Policy          `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Signature       *MsgSignature    `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	GossipMessage   *GossipMessage   `protobuf:"bytes,6,opt,name=gossipMessage,proto3" json:"gossipMessage,omitempty"`
	Probe           *Probe           `protobuf:"bytes,7,opt,name=probe,proto3" json:"probe,omitempty"`
	DatasetRequest  *DatasetRequest  `protobuf:"bytes,8,opt,name=datasetRequest,proto3" json:"datasetRequest,omitempty"`
	DatasetResponse *DatasetResponse `protobuf:"bytes,9,opt,name=datasetResponse,proto3" json:"datasetResponse,omitempty"`
	PolicyRequest   *PolicyRequest   `protobuf:"bytes,10,opt,name=policyRequest,proto3" json:"policyRequest,omitempty"`
	// Other fields
	StringValue          string   `protobuf:"bytes,14,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	StringSlice          []string `protobuf:"bytes,15,rep,name=stringSlice,proto3" json:"stringSlice,omitempty"`
	Bytes                []byte   `protobuf:"bytes,16,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	BytesSlice           [][]byte `protobuf:"bytes,17,rep,name=BytesSlice,proto3" json:"BytesSlice,omitempty"`
	BoolValue            bool     `protobuf:"varint,18,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetSender() *Node {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *Message) GetSignature() *MsgSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetGossipMessage() *GossipMessage {
	if m != nil {
		return m.GossipMessage
	}
	return nil
}

func (m *Message) GetProbe() *Probe {
	if m != nil {
		return m.Probe
	}
	return nil
}

func (m *Message) GetDatasetRequest() *DatasetRequest {
	if m != nil {
		return m.DatasetRequest
	}
	return nil
}

func (m *Message) GetDatasetResponse() *DatasetResponse {
	if m != nil {
		return m.DatasetResponse
	}
	return nil
}

func (m *Message) GetPolicyRequest() *PolicyRequest {
	if m != nil {
		return m.PolicyRequest
	}
	return nil
}

func (m *Message) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Message) GetStringSlice() []string {
	if m != nil {
		return m.StringSlice
	}
	return nil
}

func (m *Message) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Message) GetBytesSlice() [][]byte {
	if m != nil {
		return m.BytesSlice
	}
	return nil
}

func (m *Message) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

type Response struct {
	Signature            *MsgSignature `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	StringValue          string        `protobuf:"bytes,2,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	StringSlice          []string      `protobuf:"bytes,3,rep,name=stringSlice,proto3" json:"stringSlice,omitempty"`
	BytesValue           []byte        `protobuf:"bytes,4,opt,name=bytesValue,proto3" json:"bytesValue,omitempty"`
	BytesSlice           [][]byte      `protobuf:"bytes,5,rep,name=bytesSlice,proto3" json:"bytesSlice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSignature() *MsgSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Response) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Response) GetStringSlice() []string {
	if m != nil {
		return m.StringSlice
	}
	return nil
}

func (m *Response) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *Response) GetBytesSlice() [][]byte {
	if m != nil {
		return m.BytesSlice
	}
	return nil
}

// Here, node is Lohpi storage nodes, policy store and mux (and compliance engine?)
type Node struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IfritAddress         string   `protobuf:"bytes,2,opt,name=ifritAddress,proto3" json:"ifritAddress,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	ContactEmail         string   `protobuf:"bytes,4,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	Id                   []byte   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	HttpsAddress         string   `protobuf:"bytes,6,opt,name=httpsAddress,proto3" json:"httpsAddress,omitempty"`
	Port                 int32    `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetIfritAddress() string {
	if m != nil {
		return m.IfritAddress
	}
	return ""
}

func (m *Node) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Node) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetHttpsAddress() string {
	if m != nil {
		return m.HttpsAddress
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type DatasetRequest struct {
	Identifier           string        `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	ClientToken          []byte        `protobuf:"bytes,2,opt,name=clientToken,proto3" json:"clientToken,omitempty"`
	Signature            *MsgSignature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DatasetRequest) Reset()         { *m = DatasetRequest{} }
func (m *DatasetRequest) String() string { return proto.CompactTextString(m) }
func (*DatasetRequest) ProtoMessage()    {}
func (*DatasetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *DatasetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetRequest.Unmarshal(m, b)
}
func (m *DatasetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetRequest.Marshal(b, m, deterministic)
}
func (m *DatasetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetRequest.Merge(m, src)
}
func (m *DatasetRequest) XXX_Size() int {
	return xxx_messageInfo_DatasetRequest.Size(m)
}
func (m *DatasetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetRequest proto.InternalMessageInfo

func (m *DatasetRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *DatasetRequest) GetClientToken() []byte {
	if m != nil {
		return m.ClientToken
	}
	return nil
}

func (m *DatasetRequest) GetSignature() *MsgSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Dataset struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	DatasetURL           string   `protobuf:"bytes,2,opt,name=datasetURL,proto3" json:"datasetURL,omitempty"`
	MetadataURL          string   `protobuf:"bytes,3,opt,name=metadataURL,proto3" json:"metadataURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (m *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(m, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Dataset) GetDatasetURL() string {
	if m != nil {
		return m.DatasetURL
	}
	return ""
}

func (m *Dataset) GetMetadataURL() string {
	if m != nil {
		return m.MetadataURL
	}
	return ""
}

type DatasetResponse struct {
	Type                 string        `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	URL                  string        `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	IsAllowed            bool          `protobuf:"varint,3,opt,name=isAllowed,proto3" json:"isAllowed,omitempty"`
	ErrorMessage         string        `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Signature            *MsgSignature `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DatasetResponse) Reset()         { *m = DatasetResponse{} }
func (m *DatasetResponse) String() string { return proto.CompactTextString(m) }
func (*DatasetResponse) ProtoMessage()    {}
func (*DatasetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *DatasetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetResponse.Unmarshal(m, b)
}
func (m *DatasetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetResponse.Marshal(b, m, deterministic)
}
func (m *DatasetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetResponse.Merge(m, src)
}
func (m *DatasetResponse) XXX_Size() int {
	return xxx_messageInfo_DatasetResponse.Size(m)
}
func (m *DatasetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetResponse proto.InternalMessageInfo

func (m *DatasetResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DatasetResponse) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *DatasetResponse) GetIsAllowed() bool {
	if m != nil {
		return m.IsAllowed
	}
	return false
}

func (m *DatasetResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *DatasetResponse) GetSignature() *MsgSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PolicyRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyRequest) Reset()         { *m = PolicyRequest{} }
func (m *PolicyRequest) String() string { return proto.CompactTextString(m) }
func (*PolicyRequest) ProtoMessage()    {}
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *PolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyRequest.Unmarshal(m, b)
}
func (m *PolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyRequest.Marshal(b, m, deterministic)
}
func (m *PolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyRequest.Merge(m, src)
}
func (m *PolicyRequest) XXX_Size() int {
	return xxx_messageInfo_PolicyRequest.Size(m)
}
func (m *PolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyRequest proto.InternalMessageInfo

func (m *PolicyRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type MetadataRequest struct {
	Identifier           string        `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	ClientToken          []byte        `protobuf:"bytes,2,opt,name=clientToken,proto3" json:"clientToken,omitempty"`
	Signature            *MsgSignature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MetadataRequest) Reset()         { *m = MetadataRequest{} }
func (m *MetadataRequest) String() string { return proto.CompactTextString(m) }
func (*MetadataRequest) ProtoMessage()    {}
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *MetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataRequest.Unmarshal(m, b)
}
func (m *MetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataRequest.Marshal(b, m, deterministic)
}
func (m *MetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataRequest.Merge(m, src)
}
func (m *MetadataRequest) XXX_Size() int {
	return xxx_messageInfo_MetadataRequest.Size(m)
}
func (m *MetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataRequest proto.InternalMessageInfo

func (m *MetadataRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *MetadataRequest) GetClientToken() []byte {
	if m != nil {
		return m.ClientToken
	}
	return nil
}

func (m *MetadataRequest) GetSignature() *MsgSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MetadataResponse struct {
	URL                  string        `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Signature            *MsgSignature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MetadataResponse) Reset()         { *m = MetadataResponse{} }
func (m *MetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MetadataResponse) ProtoMessage()    {}
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *MetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataResponse.Unmarshal(m, b)
}
func (m *MetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataResponse.Marshal(b, m, deterministic)
}
func (m *MetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataResponse.Merge(m, src)
}
func (m *MetadataResponse) XXX_Size() int {
	return xxx_messageInfo_MetadataResponse.Size(m)
}
func (m *MetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataResponse proto.InternalMessageInfo

func (m *MetadataResponse) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MetadataResponse) GetSignature() *MsgSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Policy struct {
	Issuer               string   `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	ObjectIdentifier     string   `protobuf:"bytes,2,opt,name=objectIdentifier,proto3" json:"objectIdentifier,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *Policy) GetObjectIdentifier() string {
	if m != nil {
		return m.ObjectIdentifier
	}
	return ""
}

func (m *Policy) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MsgSignature struct {
	R                    []byte   `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S                    []byte   `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSignature) Reset()         { *m = MsgSignature{} }
func (m *MsgSignature) String() string { return proto.CompactTextString(m) }
func (*MsgSignature) ProtoMessage()    {}
func (*MsgSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *MsgSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSignature.Unmarshal(m, b)
}
func (m *MsgSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSignature.Marshal(b, m, deterministic)
}
func (m *MsgSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignature.Merge(m, src)
}
func (m *MsgSignature) XXX_Size() int {
	return xxx_messageInfo_MsgSignature.Size(m)
}
func (m *MsgSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignature.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignature proto.InternalMessageInfo

func (m *MsgSignature) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *MsgSignature) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type HandshakeResponse struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeResponse) Reset()         { *m = HandshakeResponse{} }
func (m *HandshakeResponse) String() string { return proto.CompactTextString(m) }
func (*HandshakeResponse) ProtoMessage()    {}
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *HandshakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeResponse.Unmarshal(m, b)
}
func (m *HandshakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeResponse.Marshal(b, m, deterministic)
}
func (m *HandshakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeResponse.Merge(m, src)
}
func (m *HandshakeResponse) XXX_Size() int {
	return xxx_messageInfo_HandshakeResponse.Size(m)
}
func (m *HandshakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeResponse proto.InternalMessageInfo

func (m *HandshakeResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *HandshakeResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

// Fix later
type GossipMessage struct {
	Sender               string               `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	MessageType          string               `protobuf:"bytes,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            *MsgSignature        `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	GossipMessageBody    []*GossipMessageBody `protobuf:"bytes,5,rep,name=gossipMessageBody,proto3" json:"gossipMessageBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GossipMessage) Reset()         { *m = GossipMessage{} }
func (m *GossipMessage) String() string { return proto.CompactTextString(m) }
func (*GossipMessage) ProtoMessage()    {}
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *GossipMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMessage.Unmarshal(m, b)
}
func (m *GossipMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMessage.Marshal(b, m, deterministic)
}
func (m *GossipMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMessage.Merge(m, src)
}
func (m *GossipMessage) XXX_Size() int {
	return xxx_messageInfo_GossipMessage.Size(m)
}
func (m *GossipMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMessage proto.InternalMessageInfo

func (m *GossipMessage) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *GossipMessage) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *GossipMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GossipMessage) GetSignature() *MsgSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *GossipMessage) GetGossipMessageBody() []*GossipMessageBody {
	if m != nil {
		return m.GossipMessageBody
	}
	return nil
}

type GossipMessageBody struct {
	ObjectId             string               `protobuf:"bytes,1,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Version              uint64               `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Policy               *Policy              `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GossipMessageBody) Reset()         { *m = GossipMessageBody{} }
func (m *GossipMessageBody) String() string { return proto.CompactTextString(m) }
func (*GossipMessageBody) ProtoMessage()    {}
func (*GossipMessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *GossipMessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMessageBody.Unmarshal(m, b)
}
func (m *GossipMessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMessageBody.Marshal(b, m, deterministic)
}
func (m *GossipMessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMessageBody.Merge(m, src)
}
func (m *GossipMessageBody) XXX_Size() int {
	return xxx_messageInfo_GossipMessageBody.Size(m)
}
func (m *GossipMessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMessageBody proto.InternalMessageInfo

func (m *GossipMessageBody) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *GossipMessageBody) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GossipMessageBody) GetPolicy() *Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *GossipMessageBody) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Probe struct {
	Order                uint32   `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	SessionId            []byte   `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Probe) Reset()         { *m = Probe{} }
func (m *Probe) String() string { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()    {}
func (*Probe) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *Probe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Probe.Unmarshal(m, b)
}
func (m *Probe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Probe.Marshal(b, m, deterministic)
}
func (m *Probe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Probe.Merge(m, src)
}
func (m *Probe) XXX_Size() int {
	return xxx_messageInfo_Probe.Size(m)
}
func (m *Probe) XXX_DiscardUnknown() {
	xxx_messageInfo_Probe.DiscardUnknown(m)
}

var xxx_messageInfo_Probe proto.InternalMessageInfo

func (m *Probe) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Probe) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func init() {
	proto.RegisterType((*Client)(nil), "proto.Client")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*Node)(nil), "proto.Node")
	proto.RegisterType((*DatasetRequest)(nil), "proto.DatasetRequest")
	proto.RegisterType((*Dataset)(nil), "proto.Dataset")
	proto.RegisterType((*DatasetResponse)(nil), "proto.DatasetResponse")
	proto.RegisterType((*PolicyRequest)(nil), "proto.PolicyRequest")
	proto.RegisterType((*MetadataRequest)(nil), "proto.MetadataRequest")
	proto.RegisterType((*MetadataResponse)(nil), "proto.MetadataResponse")
	proto.RegisterType((*Policy)(nil), "proto.Policy")
	proto.RegisterType((*MsgSignature)(nil), "proto.MsgSignature")
	proto.RegisterType((*HandshakeResponse)(nil), "proto.HandshakeResponse")
	proto.RegisterType((*GossipMessage)(nil), "proto.GossipMessage")
	proto.RegisterType((*GossipMessageBody)(nil), "proto.GossipMessageBody")
	proto.RegisterType((*Probe)(nil), "proto.Probe")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 936 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0x66, 0xf2, 0xd7, 0xe4, 0x24, 0x69, 0x5a, 0xb3, 0xac, 0x46, 0x15, 0x2a, 0x91, 0x11, 0x52,
	0xb4, 0x17, 0xa9, 0xe8, 0x72, 0x81, 0x40, 0x48, 0x74, 0x77, 0xd9, 0x65, 0x25, 0x8a, 0x56, 0x4e,
	0x81, 0xeb, 0x49, 0xe6, 0x34, 0x6b, 0x3a, 0x19, 0x0f, 0xb6, 0x53, 0x94, 0x07, 0x80, 0x87, 0x41,
	0x3c, 0x03, 0x12, 0x8f, 0xc0, 0x0b, 0x21, 0xe4, 0x9f, 0xf9, 0x4b, 0x2a, 0x35, 0xf4, 0x66, 0xaf,
	0xc6, 0xfe, 0xce, 0x77, 0x8e, 0xcf, 0xaf, 0x3d, 0x30, 0x54, 0x28, 0x6f, 0xf9, 0x02, 0xa7, 0x99,
	0x14, 0x5a, 0x90, 0xb6, 0xfd, 0x9c, 0x7c, 0xb4, 0x14, 0x62, 0x99, 0xe0, 0x99, 0xdd, 0xcd, 0xd7,
	0xd7, 0x67, 0x9a, 0xaf, 0x50, 0xe9, 0x68, 0x95, 0x39, 0x1e, 0x7d, 0x09, 0x9d, 0xe7, 0x09, 0xc7,
	0x54, 0x13, 0x02, 0xad, 0x34, 0x5a, 0x61, 0x18, 0x8c, 0x83, 0x49, 0x8f, 0xd9, 0x35, 0x99, 0xc0,
	0x28, 0x13, 0x09, 0x5f, 0x6c, 0x2e, 0xb4, 0x96, 0x7c, 0xbe, 0xd6, 0x18, 0x36, 0xc6, 0xc1, 0x64,
	0xc0, 0xb6, 0x61, 0xfa, 0x4f, 0x0b, 0x0e, 0x2e, 0x51, 0xa9, 0x68, 0x89, 0xc6, 0xd2, 0xd5, 0x26,
	0x2b, 0x2c, 0x99, 0x35, 0xf9, 0x18, 0x3a, 0x0a, 0xd3, 0x18, 0xa5, 0x35, 0xd0, 0x3f, 0xef, 0xbb,
	0xf3, 0xa7, 0xdf, 0x8b, 0x18, 0x99, 0x17, 0x91, 0x4f, 0xa0, 0xe3, 0xec, 0x86, 0x4d, 0x4b, 0x1a,
	0x7a, 0xd2, 0x1b, 0x0b, 0x32, 0x2f, 0x24, 0x9f, 0x42, 0x4f, 0xf1, 0x65, 0x1a, 0xe9, 0xb5, 0xc4,
	0xb0, 0x6d, 0x99, 0xef, 0x7b, 0xe6, 0xa5, 0x5a, 0xce, 0x72, 0x11, 0x2b, 0x59, 0xe4, 0x0b, 0x18,
	0x2e, 0x85, 0x52, 0x3c, 0xf3, 0x3e, 0x86, 0x1d, 0xab, 0xf6, 0xc8, 0xab, 0xbd, 0xaa, 0xca, 0x58,
	0x9d, 0x4a, 0x28, 0x98, 0x64, 0xce, 0x31, 0x3c, 0xb0, 0x3a, 0x83, 0xdc, 0x29, 0x83, 0x31, 0x27,
	0x22, 0x5f, 0xc1, 0x61, 0x1c, 0xe9, 0x48, 0xa1, 0x66, 0xf8, 0xcb, 0x1a, 0x95, 0x0e, 0xbb, 0x96,
	0xfc, 0x81, 0x27, 0xbf, 0xa8, 0x09, 0xd9, 0x16, 0x99, 0x7c, 0x0d, 0xa3, 0x02, 0x51, 0x99, 0x48,
	0x15, 0x86, 0x3d, 0xab, 0xff, 0x78, 0x5b, 0xdf, 0x49, 0xd9, 0x36, 0xdd, 0x04, 0xe8, 0xb2, 0x93,
	0x9f, 0x0f, 0xb5, 0x00, 0xdf, 0x54, 0x65, 0xac, 0x4e, 0x25, 0x63, 0xe8, 0x2b, 0x2d, 0x79, 0xba,
	0xfc, 0x31, 0x4a, 0xd6, 0x18, 0x1e, 0xda, 0xb2, 0x55, 0xa1, 0x92, 0x31, 0x4b, 0xf8, 0x02, 0xc3,
	0xd1, 0xb8, 0x59, 0x32, 0x2c, 0x44, 0x1e, 0x41, 0xfb, 0xd9, 0x46, 0xa3, 0x0a, 0x8f, 0x6c, 0x7f,
	0xb8, 0x0d, 0x39, 0x05, 0xb0, 0x0b, 0xa7, 0x76, 0x3c, 0x6e, 0x4e, 0x06, 0xac, 0x82, 0x90, 0x0f,
	0xa1, 0x37, 0x17, 0x22, 0x71, 0xe7, 0x92, 0x71, 0x30, 0xe9, 0xb2, 0x12, 0xa0, 0x7f, 0x07, 0xd0,
	0x2d, 0x02, 0xac, 0x15, 0x3d, 0xd8, 0xab, 0xe8, 0x5b, 0x71, 0x35, 0xee, 0x8d, 0xab, 0xb9, 0x1b,
	0xd7, 0x29, 0xc0, 0xdc, 0xf8, 0xeb, 0x4c, 0xb4, 0x6c, 0x70, 0x15, 0xa4, 0x90, 0x3b, 0x03, 0x6d,
	0x17, 0x61, 0x89, 0xd0, 0xbf, 0x02, 0x68, 0x99, 0x1e, 0xbf, 0x73, 0xbc, 0x28, 0x0c, 0xf8, 0xb5,
	0xe4, 0xfa, 0x22, 0x8e, 0x25, 0x2a, 0xe5, 0x3d, 0xac, 0x61, 0x46, 0x4f, 0x8a, 0x04, 0xed, 0x44,
	0xf4, 0x98, 0x5d, 0x1b, 0xbd, 0x85, 0x48, 0x75, 0xb4, 0xd0, 0xdf, 0xac, 0x22, 0x9e, 0x58, 0xb7,
	0x7a, 0xac, 0x86, 0x91, 0x43, 0x68, 0xf0, 0xd8, 0x4e, 0xc7, 0x80, 0x35, 0x78, 0x6c, 0x74, 0xde,
	0x6a, 0x9d, 0xa9, 0xfc, 0xac, 0x8e, 0xd3, 0xa9, 0x62, 0xe6, 0xac, 0x4c, 0x48, 0x6d, 0x1b, 0xbd,
	0xcd, 0xec, 0x9a, 0xfe, 0x16, 0xc0, 0x61, 0xbd, 0x7b, 0x4d, 0xcc, 0x3c, 0xc6, 0x54, 0xf3, 0x6b,
	0x8e, 0xd2, 0x07, 0x54, 0x41, 0x4c, 0x56, 0x17, 0xf6, 0x4e, 0xb9, 0x12, 0x37, 0x98, 0xfa, 0x1b,
	0xa3, 0x0a, 0xd5, 0x8b, 0xd9, 0xdc, 0xa7, 0x98, 0xf4, 0x06, 0x0e, 0xbc, 0x1b, 0xf7, 0x9e, 0x7f,
	0x0a, 0xe0, 0xc7, 0xe3, 0x07, 0xf6, 0x9d, 0x4f, 0x6a, 0x05, 0x31, 0xfe, 0xad, 0x50, 0x47, 0x06,
	0x31, 0x04, 0x97, 0xd9, 0x2a, 0x44, 0xff, 0x0c, 0x60, 0xb4, 0x35, 0x72, 0x77, 0xde, 0x6a, 0x47,
	0xd0, 0x2c, 0x8f, 0x30, 0x4b, 0xd3, 0xd1, 0x5c, 0x5d, 0x24, 0x89, 0xf8, 0x15, 0x63, 0x6b, 0xb9,
	0xcb, 0x4a, 0xc0, 0x14, 0x01, 0xa5, 0x14, 0x32, 0xbf, 0x85, 0x7c, 0xe1, 0xaa, 0xd8, 0x03, 0x6e,
	0x37, 0x7a, 0x06, 0xc3, 0xda, 0x80, 0xdf, 0x97, 0x21, 0xfa, 0x7b, 0x00, 0xa3, 0x4b, 0x1f, 0xef,
	0x3b, 0xad, 0xea, 0x4f, 0x70, 0x54, 0xfa, 0xe1, 0x13, 0xed, 0x93, 0x1a, 0x94, 0x49, 0xad, 0x19,
	0x6e, 0xec, 0x65, 0xf8, 0x1a, 0x3a, 0x2e, 0x25, 0xe4, 0x31, 0x74, 0xb8, 0x52, 0xeb, 0x22, 0x26,
	0xbf, 0x23, 0x4f, 0xe0, 0x48, 0xcc, 0x7f, 0xc6, 0x85, 0x7e, 0x5d, 0x46, 0xed, 0x0a, 0xb9, 0x83,
	0x93, 0x10, 0x0e, 0xcc, 0x70, 0x61, 0xaa, 0x7d, 0xb7, 0xe4, 0x5b, 0xfa, 0x04, 0x06, 0x55, 0x17,
	0xc8, 0x00, 0x02, 0x77, 0xd0, 0x80, 0x05, 0xd2, 0xec, 0x94, 0xcf, 0x54, 0xa0, 0xe8, 0x53, 0x38,
	0xfe, 0x36, 0x4a, 0x63, 0xf5, 0x36, 0xba, 0xc1, 0x22, 0x5a, 0x33, 0xa7, 0x99, 0x77, 0xad, 0xc1,
	0x33, 0x3f, 0xb7, 0x8d, 0x7c, 0x6e, 0xe9, 0xbf, 0x01, 0x0c, 0x6b, 0xcf, 0x93, 0x09, 0x68, 0xe6,
	0x9e, 0x52, 0x1f, 0x90, 0xdb, 0x99, 0x02, 0x79, 0x8a, 0xed, 0x53, 0x7f, 0xdd, 0x55, 0x20, 0xf2,
	0x39, 0xf4, 0x8a, 0xf7, 0xdf, 0x17, 0xe8, 0x64, 0xea, 0xfe, 0x10, 0xa6, 0xf9, 0x1f, 0xc2, 0xf4,
	0x2a, 0x67, 0xb0, 0x92, 0x5c, 0xaf, 0x40, 0x6b, 0xaf, 0xdb, 0xf7, 0x25, 0x1c, 0xd7, 0xde, 0xd1,
	0x67, 0x22, 0xde, 0xd8, 0x0b, 0xb2, 0x7f, 0x1e, 0xde, 0xf5, 0xec, 0x1a, 0x39, 0xdb, 0x55, 0xa1,
	0x7f, 0x04, 0x70, 0xbc, 0x43, 0x24, 0x27, 0xd0, 0xcd, 0xab, 0xe4, 0xd3, 0x50, 0xec, 0x4d, 0xb5,
	0x6e, 0x51, 0x2a, 0x2e, 0x5c, 0x97, 0xb6, 0x58, 0xbe, 0xdd, 0xf7, 0x07, 0xa3, 0x96, 0xa7, 0xd6,
	0xff, 0xc8, 0x13, 0xfd, 0x12, 0xda, 0xf6, 0xbf, 0xc0, 0xbc, 0x87, 0x42, 0xe6, 0x35, 0x1a, 0x32,
	0xb7, 0x31, 0xb7, 0x83, 0x42, 0x65, 0x5c, 0x79, 0x9d, 0xd7, 0xb8, 0x04, 0xce, 0x5f, 0xc1, 0xe8,
	0x05, 0x97, 0xb8, 0xd0, 0x42, 0x6e, 0x66, 0x28, 0x6f, 0x51, 0x92, 0xcf, 0xa0, 0x57, 0xb4, 0x0c,
	0xa9, 0xfe, 0x33, 0x9d, 0xe4, 0x39, 0xdc, 0xe9, 0x28, 0xfa, 0xde, 0xf9, 0x73, 0xe8, 0xbb, 0x88,
	0x66, 0x5a, 0x48, 0x7c, 0x98, 0x91, 0x79, 0xc7, 0x8a, 0x9e, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x31, 0xcb, 0x72, 0x9e, 0x59, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirectoryServerClient is the client API for DirectoryServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectoryServerClient interface {
	Handshake(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeResponse, error)
}

type directoryServerClient struct {
	cc *grpc.ClientConn
}

func NewDirectoryServerClient(cc *grpc.ClientConn) DirectoryServerClient {
	return &directoryServerClient{cc}
}

func (c *directoryServerClient) Handshake(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, "/proto.DirectoryServer/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryServerServer is the server API for DirectoryServer service.
type DirectoryServerServer interface {
	Handshake(context.Context, *Node) (*HandshakeResponse, error)
}

// UnimplementedDirectoryServerServer can be embedded to have forward compatible implementations.
type UnimplementedDirectoryServerServer struct {
}

func (*UnimplementedDirectoryServerServer) Handshake(ctx context.Context, req *Node) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}

func RegisterDirectoryServerServer(s *grpc.Server, srv DirectoryServerServer) {
	s.RegisterService(&_DirectoryServer_serviceDesc, srv)
}

func _DirectoryServer_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServerServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DirectoryServer/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServerServer).Handshake(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _DirectoryServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DirectoryServer",
	HandlerType: (*DirectoryServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _DirectoryServer_Handshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// PolicyStoreClient is the client API for PolicyStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolicyStoreClient interface {
	Handshake(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeResponse, error)
}

type policyStoreClient struct {
	cc *grpc.ClientConn
}

func NewPolicyStoreClient(cc *grpc.ClientConn) PolicyStoreClient {
	return &policyStoreClient{cc}
}

func (c *policyStoreClient) Handshake(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, "/proto.PolicyStore/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyStoreServer is the server API for PolicyStore service.
type PolicyStoreServer interface {
	Handshake(context.Context, *Node) (*HandshakeResponse, error)
}

// UnimplementedPolicyStoreServer can be embedded to have forward compatible implementations.
type UnimplementedPolicyStoreServer struct {
}

func (*UnimplementedPolicyStoreServer) Handshake(ctx context.Context, req *Node) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}

func RegisterPolicyStoreServer(s *grpc.Server, srv PolicyStoreServer) {
	s.RegisterService(&_PolicyStore_serviceDesc, srv)
}

func _PolicyStore_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyStoreServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PolicyStore/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyStoreServer).Handshake(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolicyStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PolicyStore",
	HandlerType: (*PolicyStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _PolicyStore_Handshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
