hostname: lohpi-policystore-evaluation.norwayeast.azurecontainer.io
caaddress: lohpi-cauth.norwayeast.azurecontainer.io:8301
httpport: 8083
azurekeyvaultname: "lohpi-key-vault"
azurekeyvaultsecret: "policy-store-db-connection-string-eval"
azureclientsecret: "-43gD5SuqB19l8CHlI~-lRaG2uPS~aynZd"
azuretenantid: "c628abe3-0fe1-4381-bcc0-4721d4387973"
azureclientid: "8e9cc9b6-28cd-4194-ac56-fdd52f232fcf"
azurekeyvaultbaseurl: "https://lohpi-key-vault.vault.azure.net/"
lohpicryptounitworkingdirectory: "crypto/dev/lohpi"
ifritcryptounitworkingdirectory: "kake"
ifrittcpport: 5000
ifritudpport: 8000
gossipinterval: 10
