name: "Policy Store"
host: "127.0.0.1"
httport: 8083
grpcport: 8084
gossipinterval: 10
multicastacceptancelevel: 0.5
caaddress: "127.0.1.1:8301"
directoryserveraddress: "127.0.1.1:8081"
policyStoregitrepository: "/var/tmp/lohpi/policy_store/policies"
numdirectrecipients: 1
