nodeconfig:
    muxip: 127.0.1.1:8081
    policystoreip: 127.0.1.1:8082
    lohpicaaddr: 127.0.1.1:8301
    recip: 127.0.1.1:8084
    filedigesters: 3
    fuseon: false
    root: "/home/thomas/go/src/github.com/tomcat-bit/lohpi/fs_mount"
    servehttp: true
    httpport: 8090
    fuseconfig:
        mountdirectory: "/home/thomas/go/src/github.com/tomcat-bit/lohpi/fs_mount"
