#apiVersion: 2019-12-01
location: norwayeast
name: lohpi-azureblobnode
properties:
  containers:
  - name: lohpi-azureblobnode
    properties:
      image: lohpi.azurecr.io/lohpi-azureblobnode:latest
      resources:
        requests:
          cpu: 2
          memoryInGb: 1.5
      ports:
        - protocol: UDP
          port: 8000
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 5000
  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: UDP
        port: 8000
      - protocol: TCP
        port: 9000
      - protocol: TCP
        port: 5000
    dnsnamelabel: "lohpi-azureblobnode"
  imageRegistryCredentials:
    - server: lohpi.azurecr.io
      username: lohpi
      password: jQA8j+27P11I36IOJGf9lXWwKqqbo/Ym
tags: {exampleTag: tutorial}
type: Microsoft.ContainerInstance/containerGroups