ca_addr: 127.0.1.1:8300
gossip_interval: 3
max_concurrent_messages: 5
monitor_interval: 10
ping_limit: 3
pings_per_interval: 3
removal_timeout: 3
use_ca: true
use_compression: true
use_viz: false
view_update_interval: 3
viz_update_interval: 10
