recconfig:
    muxip: 127.0.1.1:8081
    policystoreip: 127.0.1.1:8082
    recip: 127.0.1.1:8084
    lohpicaaddr: 127.0.1.1:8301
    updatepoliciesperminute: 120
    updatestudiesperminute: 60
    recdirectory: "/home/thomas/go/src/github.com/tomcat-bit/lohpi/resources/rec"
policystoreconfig:
    muxip: 127.0.1.1:8081
    policystoreip: 127.0.1.1:8082
    lohpicaaddr: 127.0.1.1:8301
    policystoregitrepository: "/home/thomas/go/src/github.com/tomcat-bit/lohpi/policy_store"
    httpport: 8083
    batchsize: 100
    multicastacceptancelevel: 0.5
