name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build --parallel 
    - name: Shut down
      run: docker-compose down
    - name: Bring up
      run: docker-compose up -d
  
